# Generated by Django 3.1.8 on 2021-08-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=20, unique=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=50)),
                ('save_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['save_at'],
            },
        ),
    ]
