# Generated by Django 3.1.8 on 2021-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardnumber',
            options={'ordering': ['-save_at']},
        ),
        migrations.AlterField(
            model_name='cardnumber',
            name='card_num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
